label fuck:
    scene black
    "The apartment door shuts behind them, they stand there for a moment, gazing to each others eyes. "
    "—breathing heavily even though nothing has happened yet."
    show bedroom with d 
    pause 1.0
    show m_neu at mjump(-1) with dissolve
    m"Have a seat wherever.."
    "He looks down, rubbing the back of his head still not making eye contact."
    hide m_neu 
    show m_disappointed at mjump(-1)
    m"I’m sorry about the mess…"
    show a_flus at ajump(600) with dissolve
    a "No — no! It’s quite alright haha we all have our days"
    "Nervously she moves towards the bed."
    "Malcolm followed suit, sitting beside along the edge of his mattress."
    a"..."
    m"..."
    a "{i}Okay Addy, {w=.25}Make a Move,{w=.25} you got this don't blow it...{/i}"
    "She takes a deep breath., then another, before turning towards the quiet man."
    "Then she makes her move."
    "Swiftly and albeit clumsily, she cups his face and moves in,"
    "She feels her heart trying to break out of her chest."
    "All her thoughts spiral at once..."
    "..."
    da "{i}Is his eyes also closed?{/i}"
    da "{i}Is he smiling{/i}"
    da "{i}does he want this?{/i}"
    da "{i}Am I doing it right?{/i}"
    da "{i}Should I stop?{/i}"
    da "{i}Did I blow it??{/i}"
    "..."
    "Their lips meet."
    "They stay there for a moment,{w=.25} but to them it felt like eternity."
    "In that moment all the thoughts built up in Adeline's head melt away."
    da"{i}No..{/i}"
    da"{i}This is right..{/i}"
    da"{i}I want this.{/i}"
    da"{i}I want him.{/i}"
    "Malcolm’ felt his face burn up as their lips entwine…"
    "For a moment he’s in shock — still. "
    "He’s never felt such closeness before.."
    "It’s intoxicating.."
    " Slowly, He wraps his arms around her waist and pulls her in close.."
    "Kissing her back — hesitantly at first before kissing her deeper."
    "Slowly, they melt into each others embrace, each others company."
    "The pressure in the room begins to thicken, the temperature rising as the pair begins to explore each others mouth."
    "Moans, groans and pants falling after each other in ecstasy."
    "He pulls back for a second much to Adeline's dismay,"
    "His hands absentmindedly rubbing tiny circles around her back."
    m "I don't.."
    m "I  want to.."
    m "I want to keep going.. pause.. If you do."
    "Adeline tilts her head slightly, confused… "
    m "What I’m saying is.. uh.. I want you. {w=.5}And I would like to—"
    "Adeline’s faint pink cheeks turn to a deep crimson,"
    "Her gaze averting to gaze at the ever so amusing floor."
    da"{i}he wants..{w=.25} Omg he wants to Fuck???.{/i}"
    da"..."
    da"I want.. I want you please.."
    da "Please take me!.."
    m"..."
    "He nods, then scoots closer again,"
    "Leaving a quick but affectionate kiss against her lips before sliding both hands along her waist and lifting her up." 
    "— receiving a yelp from the girl as a response. "
    "He moves her deeper into the bed, putting her down amongst his personal collection of plushies,"
    "Along side the shark plush they bought back at the Aquarium." 
    "Adeline's looks down at the plushies drawing her gaze away from Malcolm for a sec to settle herself."
    "She couldn't help but feel amused."
    a"{i}For a man with such a cold exterior, he sure loves cute things{/i}"
    "She's quickly pulls back to reality when she feels his hands pressed softly under the hem of her shirt. "
    a "Uwah!"
    "His hands dart away," 
    m"Oh—sorry! I just—I thought we were both undressing."
    m"I didn't mean to assume.."
    "Her eyes look up to the sight of a now shirtless Malcolm kneeling in front of her…"
    "And instead of being extremely shy— this time all she could do is gawk in awe."
    "Her eyes traced the small but perfect surgical scars that outline his pecs,"
    "Coupled with the rings of hair concentrated in the centre of his chest."
    "She then began to fixate on his just barely toned physique - his arms were slim strong ;"
    "His abdomen soft with a trail line leading her to something lewd obscured by his trousers."
    da "{i}This was real. This is happening.{/i} "
    "She started to feel hot, especially within her crotch."
    "Her cock slowly began to press against the tight denim as her mind continued to fixate on how gorgeous the man in front her was."
    m "Do you need help?."
    da"Y-Yeah. :3"
    #undress scene
    "Malcolm’s large hands returned back to the hem of her blouse, signalling her to lift her arms up before gently pulling the garment off of her." 
    "Her eyes follow his hands as her tops raises, inhaling a sharp breath when she feels the fabric parting from her body —"
    "leaving her topless all for a cute lase lase bra that held her breasts in place. "
    "He then moved closer,"
    "Gently pulling her against his chest in order to unhook her bra,"
    "His hands struggling with the clasp for a moment before managing to set her breasts free." 
    m "..."
    da"Are you okay?.."
    m"You’re beautiful.."
    "His hands move closer to touch her before stopping haphazardly," 
    "Instead hovering above her. "
    m "C—Can I touch you.."
    "She leans back, exposing herself to him as if she were inviting him in, then smiles, slowly falling in love with attention." 
    "The room felt smaller now, as it the world was only just the two." 
    "They're were close enough now to where Adeline could feel Malcolm’s hot breath pressing against her skin - "
    "Leading her to release a little mewl out of excitement."
    "Malcolm took that as his final indication that he should make his move."
    "His has began to trail along Adeline's soft, warm skin - each touch feeling like little electric shots." 
    "He grew bolder, moving his rough hand up to her small chest." 
    "He then began to caress her small chest, cupping one of her breasts in his hand and rubbing her puffy nipples between his two fingers." 
    "His other hand trailed lower, lightly wrapping his arm around her waist to keep her in place."
    "The sensation was hypnotising," 
    "Neediness spilling out in waves, moving in tandem with his touches. "
    "Her hips rolling against his tummy in order to desperately gain some sort of stimulation in her crotch."
    "She was growing needier and needier. He was growing bolder and bolder in response."
    da "Fu—Fuck… Malcolm,,,"
    da "Please,,, u—uha"
    "A warm heat grew wilder and hotter in his core, his T dick throbbed in tandem with Adeline's bulge as it grinded wantonly onto him." 
    "Her cute moans egged him on further, threatening his mind to slip deep into his repressed perverted desires. "
    m "A—Addy.."

    "His head dipped, his wet mouth latching on to her nipple—" 
    "Sucking hard before rolling the underside of his tongue around it over and over again."
    "Adeline yelped in surprise, before letting out a loud and shameless moan, "
    "Grabbing the back of his head to push him to suck harder."
    "He pulled back a bit, worry flashing across his usually apathetic face.."
    m "Shit, I’m s—sorry."
    m "Was it too much.."
    "No No, not at all!"

    da "Actually it was amazing,"
    "She bucked her hips along his tummy as an invitation.."

    da"Can you do it again.."

    m"Are you sure,?"

    "He cupped her cheek.."

    da"mhph!"
    m "Alright.."
    "Slowly, he peppered multiple deliberate kissed down her chest down to her soft tummy." 
    "He then moved to her jeans, frantically popping the button and unzipping the denim before yanking both jean and boxers together in one go."
    "Her cock sprung fee, already leaking heavily from anticipation."
    "Malcolm stopped for a second, admiring the view before running a slow long line from her bush to the tip with is fore finger."
    da"nhgnn.. f—fuck mal…"
    da"s—stop teasing  me."
    "Malcolm leaned forward, hand clasped over her throbbing member, pumping it as they kissed."
    dm "I—I want to feel you against me..,"
    "Adeline blinked,{w=.25} the gears turning in her mind before clocking.. "
    "She let out a devious chuckle for reaching for Malcolm’s already half undone trousers, before taking it off."
    "His T-dick stood proudly, throbbing as a response to previous stimuli." 
    "Slick and hard with is own arousal."
    a "I—It’s so big"
    m "Do—Do you think so.."
    "Adeline tucked the cock neatly between her two fingers before rubbing her palm against his mound.."
    dm "F—fuck, Addy,,, slowerr please.,,"
    "Malcolm mewled into the touch," 
    "Wrapping his arms around her shoulders and tucking his head into the crook of her neck as if he was holding on for dear life.."
    dm "So—So soft.."
    dm "You're hands so soft Ade,,"
    dm "So so sof—ahn,,"
    "His hips jerked up to meet the base of her palm.."
    dm "I’ve.. i’ve nnever felt anythiung like this beforoe.."
    da "Do you believe me now~"
    dm "Ahg,.. <3"
    da "You're so vocal..<3 I didn't think you had it in you.."
    "His head dug deeper into the crook of her neck in embarrassment.." 
    "She really was a people’s person." 
    "She knew all the right words to push him off the edge."

    #frot
    "Her slender fingers slightly teases his entrance before slipping away."
    "Instead nudging him to lie on his back upon the mountain of stuffed animals."
    "The plushies rustled under him as Adeline spread his toned but lanky thighs to settle herself between him. "
    "Her throbbing cock rested on top of his lower stomach, leaking beads of precum. As he waited, he swallowed hard, waiting for her next move.. "
    show frot_start with d
    "Slowly, She straddled his hips so her thighs mirrored his. She then wrapped gently her dainty fingers around both their lengths."
    "While her cock was longer and thicker, his shorter, harder shaft felt riveting against her length."
    " Aligning them, she began to slowly grin forward, a mixture of her pre cum and his arousal slicking the skin. "
    show frot_during with d  
    hide frot_start 
    a "It’s twitching so much,,,{w=.25} fuck you must be really excited.."
    " It was clear from his soft, almost closed eyes - partnered with his blown pupils,"
    "That he had fell deeper and deeper into lust the harder she ground into him."
    "His hips jerking up as a sign of approval.."
    da "D—Does it feel good baby."
    da "Am I making you feel good?"
    dm "Yes,"
    dm "Yes!"
    "Malcolm's head nodded frantically, one hand now gripped against his blanket as he attempted to keep his composure."
    " But how could be when it felt like heaven on earth."
    "The wet noises of the two grinding on each other,"
    "Their slick heads kissing and rubbing each other in tiny circles."
    " He could not get enough.."
    dm "Addy,,, Oh addy pleasse—"
    "The girl leaned closer, attempting to hear the whimpers of the once rigid man.."
    "The slickness and the position causing her slick head to run along his wet entranced up to his throbbing cock with each thrust of hee hips."
    "Slowly she picked up the pace, attempting to hear more and more out of him."
    "Longer firmer grinds now pushing the two off the edge in rhythmic strokes."
    "Lewd noises growing louder and louder as her balls slapped against him with each roll."
    "Shamefully, his hand slid up to grip her shapely ass, pulling her down in pure greed.."
    da "Mal— oh mal."
    da "You-re so cute like this <3"
    da"Everything about you, is so—so cute and handsome.."
    dm "T—Thank you,,"
    dm "I want— I want to be your handsome boy,,"
    "Her lips hungrily capture his mouth — stealing lewd and sloppy kisses... "
    "Their touches explored each nook and cranny of each others mouths both slowly reaching their climax.."
    da"Mall—"
    da "I'm—"
    da "I'm gonna comee..."
    da "Fuck!"
    show frot_climax with d 
    hide frot_during
    da "Ngh—"
    da "So—.."
    da "So much is leaking out,,"
    da "It's so messy, I've covered you..."
    dm "Do.."
    dm "Do you think you're going to leak anymore.."
    da "What do you mean?"
    dm"I-"
    dm "Um.."

    m"My Mouth,,"
    m"Please.."
    m"Please cum in my mouth,,"
    a "You're such a pervert <33"
    m"Please Addy, I want to swallow you,,"
    "Adeline hooked her hands under Malcolm's arms, pulling up onto his knees before standing up"
    "Her free hand rolled Malcolm's fluffy locks back, signalling him to part his mouth before guiding her slick cock into his warm moist mouth.."
    show suck_start with dissolve
    pause 1.5
    show suck_during with dissolve
    hide suck_start
    hide frot_climax
    pause 1
    "Desperate for release, she began to thrust deeply into the boy’s mouth,"
    "Her thick cock rubbing across his wet tongue desperately chasing her release."
    "Malcolm looked up at her with puppy eyes, the most emotion he’d shown since shed met him,"
    "A Desperate yelp hummed across her length as he pumped him self."
    da"I-I'm so deep inside you,{w=.25} f—fuck I need you"
    dm"{cps=50}I need tyou{/cps} "
    dm"{cps=50}I nweed you{/cps}"
    show suck_climax with dissolve
    hide suck_during
    da "Malcolm Ilove you, I love you — {w=.25}please please"
    da "Can—{w=.25} Can I cum down your throat..."
    dm"P—Please.."
    dm"F—Fill me,"
    da"Fuck Malcolm."
    da"{cps=30}I'm Cumming{/csp}"
    da"{cps=30}I—I’m cummingg{/cps}"
    "In one last stroke, she thrusts deep into his mouth,"
    show suck_end with dissolve
    hide suck_during
    hide suck_climax
    "Her thick seed sputtering into his throat, Malcolm taking all of it like the good boy he is.."
    "In a mix of ecstasy and exhaustion, they both collapse on to the bed, holding each other close as they cool down for round 2."
    hide suck_end with fade
    a "W—Was I good ,,"
    m "You were really good, {w=.25} I’ve not felt anything like this,,"
    a "Is this your first time.."
    m "..."
    m "Yeah.."
    a "You're my first too,,"
    m "I'm glad.."
    "He plastered a sweet kiss on her forehead, {w=.25}absentmindedly rocking his own cock in tired lewdness."
    scene black 
    show text "{color=#ffffff}Fast Forward...{/color}" with d 
    pause 1 
    hide text with d

    da "Can—Can I suck you,,"
    da "You didn’t get to cum—"
    "Malcolm, too shy to audibly reply, nod instead, spreading his legs to give the girl access."
    "Adeline got up, kneeling between his thighs - admiring the view."
    show head_start with  dissolve
    da "I know I’ve already said this but you’re so hung,,"
    "She leans down, getting a better look of his cock to Malcolm’s horror. "
    da "Awe, does this turn you on?"
    dm "H—Hey,, don’t tease me.."
    "Tucking her hair bank, she dragged her wet tongue against the based of his cock, slightly nibbling on the head to see how he’d react."
    show head_during with d
    hide head_start

    dm "Fuck, ahg—"
    da "hehe.."
    "She grinned deviously, before taking him fully in her mouth. Wet slurping sounds filling the room as she went slow on him.."
    da"You-you're throbbing so much.."
    da"Be vocal Malcolm tell me how you feel,,"
    da "You don’t need to behave around me remember,,"
    dm "Fuck,"
    dm "You feel so good.,,ngh"
    "One hands rested gently onto Adeline's head."
    "Slowly, he seized control, the roll of his hips guiding Adeline's head as she bopped up and down on him. "
    dm "D-Do you like that?"
    dm "Do you like having your throat fucked like a w-whore?"
    "A wave of ecstasy shot through Adeline's body,"
    "The words causing her cock to begin leaking again."
    dm"Answer me, A-adeline."
    da "I love it..."
    da "I love being your little slut Malcolm!"
    da "M—My throat is made for you to fuck it,,"
    dm "Good,,"
    "He slowly ramped up the pace, now slamming his hips into her face as he rapidly reached his climax.."
    "Adeline's breath hitched around his cock, the vibrations ripping deeper groans from his core.."
    dm"I-I’m about to cum, f—fuck <3"
    dm "Adeline let me spill my love into you, p—please"
    da "Claim me Mal —-nght,,"
    show head_climax with d
    hide head_during
    "Malcolm's senses overwhelmed by pure ecstasy as his loved spilled hotly across her tongue,,"
    dm "B-be my good girl {w=.25}— huff —{w=.25} and swallow it all,,"
    "Deep gulps from Adeline resulted in Malcolm cupping her cheek and rubbing her head as if he was petting a dog,,."
    hide head_climax with d
    da"Mmmmm :3"
    "Malcolm slowly got up, Pulling the girl into her lap, paying extra attention to her ass.."
    da"Slut shaming?"
    da "That’s so pervy,,"
    da "I didn't know you were like that,,"
    m "I think you just bring that side out of me >///<"
    m "hmm?"
    "Malcolm's fingers slowly wandered around Adeline's lower half." 
    "First tracing hearts all over her thighs before sneakily making her way to her asshole. Slowly tracing circles around the ring.."
    m "You know, you’ve been such a good girl today. I think you deserved to be fucked.."
    da "Wah—"
    "His fingers made their way to his quivering pussy,"
    "Coating themselves in the juices it accumulated through all the fucking." 
    "They then traveled their way back to Adeline’s hole, slowly prodding it before stretching her to accommodate themselves."
    "Adeline’s head dropped, her eyes clenched as he grew accustomed to the unfamiliar but addicting new sensation.. "
    m "Do you want to be fucked Adeline?"
    da "mhph..!"
    m "Use your words princess.."
    m "Do {w=.25}you {w=.25}want {w=.25}to {w=.25}get {w=.25}fucked… Adeline..?"
    da "Ngh—Yes, Yes sir.."
    m "Good girl,,"
    "Malcolm slowly lifts her up, laying her down back into the throne of plushies, "
    "Leaning down slowly to whisper something in her ear,"
    m "Go ahead and touch your self my greedy girl,, make sure you get nice and hard for me,,"
    "Adeline nod in submission, slowly rubbing circles around her nipple while Malcolm slipped away to prepare."
    "He pulled the middle shelf from his bedside table," 
    "pulling out a bottle of water based lubricant, and a stroker embedded strap with a harness." 
    "Slowly and methodically like he was once before," 
    "He squeezed a hefty amount of lube in the hole where his t dick was supposed to go,"
    "Before slipping a finger in to ensure everything was properly lubricated."
    "He then meticulously stepped into the harness," 
    "Lining up his length with the whole before pulling the back harness tight" 
    "Once he was ready, he returned back to the bed, lube in hand.."
    "Adeline watched the man closely, for some reason his carefulness and attention to detail turned her on further." 
    da"{i}For a virgin, he sure was educated.{/i}"
    da"{i}I wonder how long he’d been waiting to meet a girl like me,,.{/i}"
    "Malcolm’s large hands rested in the circle of her back upper thighs," 
    "Slowly separating them back to expose her twitching hole.. "
    "I’m glad you're so desperate princess.. <3"
    "He pours a bit of the lube onto his forefinger," 
    "Barely pushing it in and out of her as a way of teasing her,,."
    da"M—Malcolm please,,"
    da "No more,, I — I need you,,"
    m "Oh?"
    "Gently, He squeezed more cool lube onto her quivering entrance," 
    "Causing her to yelp at the temperature difference."
    m"Are you ready...?"
    da "P—Pleasee,"
    "Malcolm's hands grip tightly on to Adeline's waist," 
    "Almost using her as a handle to thrust as deep as possible,,"
    "Gently rocking his hips," 
    "Malcolm's made sure to move to a slow gentle rhythm —{w=.25} as if he was pumping his love into her bit by bit.."
    da "Ahngg— <3 You're cock fills so big inside me,, you're stretching me outt,,"
    "The boy, overwhelmed with lust and ecstasy, leaned forward, taking him her intoxicating smell.. "
    "God everything about her is perfect, her small but shapely breasts," 
    "Her ample ass, her beautiful soft tanned skin."
    "Her Short bouncy hair, her bright inviting eyes." 
    "Her random tidbits, her silly jokes, her tendencies to filler out her sentences."
    "Her open mind. "
    "..."
    "Everything. "
    "He loved everything about her." 
    "He wanted everything about her to be his. "
    "He wanted her to be his."
    "He loved her."
    "He began to tighten his grip around her wait," 
    "Ramping up his thrusts in desperation." 
    "He felt good, he felt good making her feel good." 
    "Each thrust milked a cute little thrust out of her." 
    da "M—Mal, Oh fuck,,,"
    "She sounded so slutty the way she moaned his name and rocked her wide hips against his length.."
    "It was too much."

    "He started experimenting,{w=.25} trying to reverse engineer difference ways he could get new moans out of her,"
    "He’d pull out all the way to the tip — before slamming it right back into her. "
    "Causing her small frame to jerk almost violently against his cock."
    "He’d angle his thrusts too to perfectly stimulate her prostate," 
    "Causing copious amounts of pre cum to dribble out of her delectable member."
    da "F—Fuck, Harder… Harderr, please Malcolml.."
    da "Pounds me… Pound me…, "
    da "Make your needy girl scream.."
    "Her back arched against him, her needy length desperately rubbing itself again his tummy…"
    "He pushed himself back, now towering over her, his hands clasped within hers."
    "His eyes glazed over, as he stared desperately and almost obsessively into her very being."
    dm "I love you."
    dm "I love you Adeline I love you."
    dm "I want to make you mine princess."
    "Tears start to leak from both their eyes,"
    "Pure lust and a burning desire beginning to spread through ever inch of their bodies."
    dm "I lvoe you,"
    dm "I love you."
    dm "I love you"
    dm "f—fUCK."
    dm "I LOVE YOU."
    dm "I need you I need You I need you."
    da "Mal.. Oh mall —- I'm <3 I’m so close.."
    da "Take me, fuvk—Claim me as your dirty slut."
    da "I want to be your princess.."
    da "PLease—<3"
    da "F-Fuck,— fuck —Malcolm I-m close <3 ahnng— fuck don't stop don't stop."
    da "Breed me,,, please——<3"
    da "Cum inside your good girl.,,"
    da "Make me leak all over you…"
    dm "F—Fuckk,,"
    da "I’mm Cumming..,,,,fuckk—-ahgh,..<3"
    "With a final jolt from Malcolm, multiple ropes of white cream sputtered from Adeline's twitching shaft."
    "Her walls holding an iron grip onto Malcolm’s cock as she riles with ecstasy."
    "Malcolm collapsed on top of her, feeling exhausted and strangely complete.."
    "The world goes still, It’s just the two of them. In total harmony.."
    "With heavily lids, sleep beginning to creep over them. Being claimed by exhaustion.."
    da "Malcolm…"
    da "Did you mean it.."
    m "Hmm?"
    da "Did you mean it, {w=.25} when you said you loved me."
    "Malcolm's shuffled slightly closer, wrapping his arms around his clumsy girl.."
    "He leans in, leaving a rather sloppy but authentic kiss on her cheek.."
    m"Absolutely..{w=.25} I love you Adeline.."
    da "I—I’m glad…."
    da "..."
    da "I love you too.. {w=.25}since the day I saw you,,"
    m"mmm, When you spilt hot coffee on me..?"
    a "When I spilt hot coffee on you.,,"
    da"{cps=25}Thank you.{/cps}"

    da"{cps=25}For everything..{/cps}"
    
    scene black
    #end 

    "It was any other unremarkable Tuesday," 
    "Business{w=.25} - while not failing,{w=.25} - was as quiet and slow like any other day"
    " Couples,{w=.25} Normies,{w=.25} the occasional tourist or two would come,{w=.25} order,{w=.25} read and leave."
    "The quiet atmosphere was something Adeline knew too well."
    "But all of that would lighten up when her favorite customer{w=.25} — now boyfriend —{w=.25} came to get his daily coffee."
    m"Can I have a black coffee please."
    a "..."
    a"Always... <3 "
    scene black
    return